[package]
name = "interfacer-http"
version = "0.0.1"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"
license = "MIT"
description = "SDK builder for HTTP API, like retrofit"
repository = "https://github.com/Hexilee/interfacer"
keywords = ["SDK-Builder"]
categories = ["api-bindings"]
readme = "README.md"
documentation = "https://docs.rs/interfacer-http"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/lib.rs"

[dependencies]
interfacer = { path = "..", version = "0.0" }
quote = "0.6"
proc-macro2 = "0.4"
synstructure = "0.10"

[dependencies.syn]
version = "0.15"
features = ["full"]